### ISSUE TITLE
Add Salvage Logging to Base Harvest?

### ISSUE THREAD

**Issue by lbross** [LANDIS-II-Foundation/Extension-Base-Harvest#1]
Reported by lbross@pdx.edu, Oct 22, 2014
From Caren Dymond: I was wondering if you would be willing to add a sort type parameter for standing snag biomass. This would allow simulation of salvage harvesting - a big deal in the west with the pine beetle epidemic and in the boreal with forest fires.

I can share the ForCS code so you can see which pool in the site cohorts would need to be used for sorting.

GoogleCode Issue 41

**Comment by bmarron18** [comment]
This issue can be closed. Passed QAQC (see attached)

[PWL77a3_QAQC_SalvageLogging_20170904.txt](https://github.com/LANDIS-II-Foundation/Extension-Base-Harvest/files/1275600/PWL77a3_QAQC_SalvageLogging_20170904.txt)
