### ISSUE TITLE
CompleteStandSpread requires 2 size parameters - not in User Guide

### ISSUE THREAD

**Issue by brmiranda** [LANDIS-II-Foundation/Extension-Base-Harvest#26]
When using CompleteStandSpread for the SiteSelection method, the extension expects 2 input parameters to follow.  However the User Guide only lists one target size parameter.  Based on the code it looks like the 2 expected parameters are minTargetSize and maxTargetSize.  The User Guide basically implies that the minTargetSize would be 95% of the maxTargetSize, but at some point this became a separate input parameter.  This probably just requires an update to the documentation.  Note that this appears to apply equally to StandSpreading and PartialStandSpreading.

**Comment by rmscheller** [comment]
Good catch - thanks!

**Comment by rmscheller** [comment]
Corrected and uploaded.  Will be included in next release.
