### ISSUE TITLE
AllExceptOldest Not Working

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Base-Harvest#28]
From a diligent user:

 "Error reading input value for Age or Age Range: AllExceptOldest is not a valid integer". The model doesn't like AllExceptOldest keyword in my harvest file which I don't know why.

**Comment by bmarron18** [comment]
This does not appear to be a reproducible issue.  As a test, base-harvest_SetUp_s1e1.txt was modified. The prescription, OakPatchCutting in base-harvest_SetUp_s1e1.txt contains the cohort keyword "AllExceptOldest". This prescription was modified along with  base-harvest_SetUp_s1e1.txt to ensure its realization. Checking the output in base-harvest-event-log.csv confirmed the prescription using  cohort keyword "AllExceptOldest" was implemented. Perhaps there is an operator error?

Issue should be closed.

[PWL85_QAQC_ALLEXCEPTOldest_20171005 .txt](https://github.com/LANDIS-II-Foundation/Extension-Base-Harvest/files/1366322/PWL85_QAQC_ALLEXCEPTOldest_20171005.txt)

**Comment by rmscheller** [comment]
From our dear user:
 It did not work when I was using the commands "All" and "AllExceptOldest" for each species in the SpeciesList (see the attached harvest_scratch.text), but I got it to run after replacing those with age ranges for each species in the SpeciesList  (see the attached harvest_scratch3.text). According to the user guide I thought I could use "All" and "AllExceptOldest" for each species but it didn't work that way. Maybe that's just the way the model works?
